name: C++ Test Suite

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/*_cpp.yml
      - bindings/cpp/**
      - src/**
      - Cargo.lock
      - Cargo.toml
      - deny.toml
      - .gitmodules
  pull_request:
    paths:
      - .github/workflows/*_cpp.yml
      - bindings/cpp/**
      - src/**
      - Cargo.lock
      - Cargo.toml
      - deny.toml
      - .gitmodules

permissions:
  contents: read

jobs:
  test:
    name: C++ test
    defaults:
      run:
        working-directory: bindings/cpp
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            cmake_flags: -DBUILD_WITH_CHECK_COVERAGE=ON
    runs-on: ${{matrix.os}}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@d0592fe69e35bc8f12e3dbaf9ad2694d976cb8e3 # stable
      - uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
      - name: Make Build Directory
        run: mkdir -p build
      - name: CMake Configure
        working-directory: bindings/cpp/build
        run: |
          # Make cmocka a static dependency when testing.
          cmake ../ -DBUILD_SHARED_LIBS=OFF -DBUILD_CPPCHECKS_TESTS=ON ${{ matrix.cmake_flags }}
      - name: CMake Build
        working-directory: bindings/cpp/build
        run: |
          cmake --build . --config=Debug
      - name: Run Test
        working-directory: bindings/cpp/build
        run: ctest -C Debug -VV --output-on-failure
      - name: Run Valgrind
        working-directory: bindings/cpp/build
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install -y valgrind
          valgrind -v --leak-check=full --show-leak-kinds=all tests/test_item
          valgrind -v --leak-check=full --show-leak-kinds=all tests/test_result
          valgrind -v --leak-check=full --show-leak-kinds=all tests/test_runner
          valgrind -v --leak-check=full --show-leak-kinds=all tests/test_status
      - name: Run LCov
        working-directory: bindings/cpp/build
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install -y lcov
          lcov -c -d . -o coverage.info
      - uses: codecov/codecov-action@5ecb98a3c6b747ed38dc09f787459979aebb39be # v4.3.1
        with:
          flags: lang-cpp
          files: build/coverage.info
